{
 "title": "Intel GPU",
 "tags": [
  "unraid",
  "prometheus",
  "intel"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "igpu_instance",
    "query": {
     "query": "label_values(igpu_power_gpu,instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Intel GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "igpu_power_gpu{instance=\"$igpu_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video Engines Load",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "igpu_engines_busy_percent{instance=\"$igpu_instance\"}",
     "legendFormat": "{{engine}}"
    }
   ]
  },
  {
   "title": "GPU memory use by process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "igpu_client_memory_active_bytes",
     "legendFormat": "{{name}} {{pid}}"
    }
   ]
  },
  {
   "title": "GPU engine use  by process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_client_engine_busy_percent{instance=\"$igpu_instance\"}",
     "legendFormat": "{{name}} {{pid}} {{engine}}"
    }
   ]
  }
 ]
}